jenkins:
  enabled: true
  controller:
    jenkinsUrl: https://jenkins.dusktify.com/
    jenkinsUrlProtocol: https
    resources:
      limits:
        cpu: "1024m"
        memory: "1024Mi"
      requests:
        cpu: "512m"
        memory: "512Mi"
  agent:
    resources:
      limits:
        cpu: "512m"
        memory: "512Mi"
      requests:
        cpu: "512m"
        memory: "512Mi"