jenkins:
  enabled: true
  controller:
    jenkinsUrl: https://jenkins.dusktify.com/
    jenkinsUrlProtocol: https
    # Complete list of plugins
    installPlugins:
      # Core and API plugins
      - antisamy-markup-formatter
      - apache-httpcomponents-client-4-api
      - asm-api
      - authentication-tokens
      - bouncycastle-api
      - branch-api
      - caffeine-api
      - checks-api
      - commons-lang3-api
      - commons-text-api
      - configuration-as-code
      - credentials-binding
      - credentials
      - display-url-api
      - durable-task
      - echarts-api
      - font-awesome-api
      - gson-api
      - handy-uri-templates-2-api
      - instance-identity
      - ionicons-api
      - jackson2-api
      - jakarta-activation-api
      - jakarta-mail-api
      - javax-activation-api
      - jaxb
      - jjwt-api
      - joda-time-api
      - jquery3-api
      - json-api
      - json-path-api
      - mina-sshd-api-common
      - mina-sshd-api-core
      - okhttp-api
      - plugin-util-api
      - prism-api
      - scm-api
      - script-security
      - snakeyaml-api
      - ssh-credentials
      - structs
      - token-macro
      - variant
      
      # UI and visualization
      - blueocean-bitbucket-pipeline
      - blueocean-commons
      - blueocean-config
      - blueocean-core-js
      - blueocean-dashboard
      - blueocean-display-url
      - blueocean-events
      - blueocean-git-pipeline
      - blueocean-github-pipeline
      - blueocean-i18n
      - blueocean-jwt
      - blueocean-personalization
      - blueocean-pipeline-api-impl
      - blueocean-pipeline-editor
      - blueocean-pipeline-scm-api
      - blueocean-rest-impl
      - blueocean-rest
      - blueocean-web
      - blueocean
      - bootstrap5-api
      - favorite
      - htmlpublisher
      - jenkins-design-language
      - pubsub-light
      - sse-gateway
      
      # Source control
      - git-client
      - git
      - github-api
      - github-branch-source
      - github-pullrequest
      - github
      - cloudbees-bitbucket-branch-source
      
      # Kubernetes integration
      - kubernetes-cli
      - kubernetes-client-api
      - kubernetes-credentials-provider
      - kubernetes-credentials
      - kubernetes
      
      # Pipeline and workflow
      - pipeline-build-step
      - pipeline-github-lib
      - pipeline-github
      - pipeline-graph-analysis
      - pipeline-groovy-lib
      - pipeline-input-step
      - pipeline-milestone-step
      - pipeline-model-api
      - pipeline-model-definition
      - pipeline-model-extensions
      - pipeline-rest-api
      - pipeline-stage-step
      - pipeline-stage-tags-metadata
      - pipeline-stage-view
      - workflow-aggregator
      - workflow-api
      - workflow-basic-steps
      - workflow-cps
      - workflow-durable-task-step
      - workflow-job
      - workflow-multibranch
      - workflow-scm-step
      - workflow-step-api
      - workflow-support
      
      # Utility plugins
      - cloudbees-folder
      - junit
      - mailer
      - matrix-project
      - metrics
      - plain-credentials
      - purge-job-history
      - resource-disposer
      - ws-cleanup
      
    # JCasC:
      # IMPORTANT: Only include securityRealm when using GitHub OAuth for SSO
      # If not using GitHub OAuth, remove this section
      # securityRealm: |-
      #   github:
      #     clientID: "YOUR_GITHUB_CLIENT_ID"
      #     clientSecret: "YOUR_GITHUB_CLIENT_SECRET"
      #     githubApiUri: "https://api.github.com"
      #     githubWebUri: "https://github.com"
      #     oauthScopes: "read:org,user:email,repo"
      # authorizationStrategy: |-
      #   roleBased:
      #     roles:
      #       global:
      #       - entries:
      #         - user: "YOUR_GITHUB_USERNAME"
      #         - user: "admin"
      #         name: "admin"
      #         pattern: ".*"
      #         permissions:
      #         - "Overall/Administer"
      #       - entries:
      #         - group: "authenticated"
      #         name: "dev"
      #         pattern: ".*"
      #         permissions:
      #         - "Overall/Read"
    resources:
      limits:
        cpu: "1024m"
        memory: "1024Mi"
      requests:
        cpu: "512m"
        memory: "512Mi"
  agent:
    resources:
      limits:
        cpu: "512m"
        memory: "512Mi"
      requests:
        cpu: "512m"
        memory: "512Mi"